# Generated by Django 4.2 on 2023-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_paymentmodel_ptype_delete_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='pdone',
            field=models.BooleanField(default=False),
        ),
    ]
