# Generated by Django 4.2 on 2023-04-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_reservationmodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='r_car',
            field=models.CharField(max_length=1000),
        ),
    ]
