# Generated by Django 4.2 on 2023-04-20 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_reservationmodel_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='booked',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
