# Generated by Django 4.2 on 2023-04-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_reservationmodel_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='payment',
        ),
    ]
