# Generated by Django 4.2 on 2023-04-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_reservationmodel_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='pbook',
            field=models.ForeignKey(default=3432, on_delete=django.db.models.deletion.CASCADE, to='customer.reservationmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
