# Generated by Django 4.2 on 2023-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_paymentmodel_ptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='status',
            field=models.CharField(choices=[('PANDING', 'PANDING'), ('DELIVERD', 'DELAVERD'), ('CANCEL', 'CANCEL'), ('RETURN', 'RETURN')], max_length=100, null=True),
        ),
    ]
