# Generated by Django 4.2 on 2023-05-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_reservationmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='ed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='st_date',
            field=models.DateField(null=True),
        ),
    ]
