# Generated by Django 4.2 on 2023-05-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_reservationmodel_ed_date_reservationmodel_st_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='ed_date',
            new_name='return_date',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='st_date',
        ),
    ]
