# Generated by Django 4.2 on 2023-04-16 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_com', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'carcompany',
            },
        ),
        migrations.RenameField(
            model_name='car',
            old_name='carname',
            new_name='car_model',
        ),
        migrations.AddField(
            model_name='car',
            name='carcompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carcompany'),
        ),
    ]
