# Generated by Django 4.2 on 2023-04-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carcompany_rename_carname_car_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='desc',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='lice_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars_images/'),
        ),
    ]
