# Generated by Django 4.2 on 2023-04-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_desc_car_lice_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='lice_image',
            new_name='car_image',
        ),
    ]
