# Generated by Django 4.2 on 2023-04-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='decs',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lice_image',
            field=models.ImageField(blank=True, default='default-pic.jpg', null=True, upload_to='licence_image/'),
        ),
        migrations.AddField(
            model_name='user',
            name='licence',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='prof_image',
            field=models.ImageField(blank=True, default='default-pic.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
